<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <LangVersion>latest</LangVersion>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\SignalNine.Core\SignalNine.Core.csproj" />
    <ProjectReference Include="..\SignalNine.Persistence\SignalNine.Persistence.csproj" />
  </ItemGroup>

</Project>
